# Generated by Django 3.0.6 on 2020-05-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pet',
            name='submitter',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
